
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.Interact
{
    /// <summary>
    /// 单个物品信息
    /// </summary>
    public sealed partial class ItemInfo : Luban.BeanBase
    {
        public ItemInfo(JToken _buf)
        {
            JObject _obj = _buf as JObject;
            Id = (int)_obj.GetValue("id");
            Rarity = (ERarity)(int)_obj.GetValue("Rarity");
            Itemype = (EItemype)(int)_obj.GetValue("Itemype");
            ItemName = (string)_obj.GetValue("ItemName");
            ItemDescription = (string)_obj.GetValue("ItemDescription");
            ItemIcon = (string)_obj.GetValue("ItemIcon");
            Weight = (int)_obj.GetValue("Weight");
            Height = (int)_obj.GetValue("Height");
        }

        public static ItemInfo DeserializeItemInfo(JToken _buf)
        {
            return new Interact.ItemInfo(_buf);
        }

        /// <summary>
        /// 主键
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 稀有度
        /// </summary>
        public readonly ERarity Rarity;
        /// <summary>
        /// 道具类型
        /// </summary>
        public readonly EItemype Itemype;
        /// <summary>
        /// 道具名称
        /// </summary>
        public readonly string ItemName;
        /// <summary>
        /// 道具描述
        /// </summary>
        public readonly string ItemDescription;
        /// <summary>
        /// 图标路径（Resources）
        /// </summary>
        public readonly string ItemIcon;
        /// <summary>
        /// 重量
        /// </summary>
        public readonly int Weight;
        /// <summary>
        /// 高度
        /// </summary>
        public readonly int Height;


        public const int __ID__ = 364654361;
        public override int GetTypeId() => __ID__;

        public void ResolveRef(Tables tables)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "Rarity:" + Rarity + ","
            + "Itemype:" + Itemype + ","
            + "ItemName:" + ItemName + ","
            + "ItemDescription:" + ItemDescription + ","
            + "ItemIcon:" + ItemIcon + ","
            + "Weight:" + Weight + ","
            + "Height:" + Height + ","
            + "}";
        }
    }
}

