
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.Interact
{

    /// <summary>
    /// 某张表包含所有物品的信息
    /// </summary>
    public partial class TbItemInfo
    {
        private readonly System.Collections.Generic.Dictionary<int, Interact.ItemInfo> _dataMap;
        private readonly System.Collections.Generic.List<Interact.ItemInfo> _dataList;

        public TbItemInfo(JArray _buf)
        {
            /// 表格信息类数据字典
            _dataMap = new System.Collections.Generic.Dictionary<int, Interact.ItemInfo>(_buf.Count);
            
            // 表格信息类数据列表
            _dataList = new System.Collections.Generic.List<Interact.ItemInfo>(_buf.Count);

            foreach (JObject _ele in _buf)
            {
                Interact.ItemInfo _v;
                _v = global::cfg.Interact.ItemInfo.DeserializeItemInfo(_ele);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }

        //属性
        public System.Collections.Generic.Dictionary<int, Interact.ItemInfo> DataMap => _dataMap;
        public System.Collections.Generic.List<Interact.ItemInfo> DataList => _dataList;

        public Interact.ItemInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
        public Interact.ItemInfo Get(int key) => _dataMap[key];
        public Interact.ItemInfo this[int key] => _dataMap[key];

        /// <summary>
        /// 解析引用
        /// </summary>
        /// <param name="tables"></param>
        public void ResolveRef(Tables tables)
        {
            foreach (var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }

    }
}

