
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EItemype
    {
        战利品 = 0,
        枪械 = 1,
        消耗品 = 2,
        投掷物 = 3,
    }

} 

