
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ERarity
    {
        白 = 0,
        绿 = 1,
        蓝 = 2,
        紫 = 3,
        金 = 4,
        红 = 5,
    }

} 

