
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
    /// <summary>
    /// 所有表格的管理器
    /// </summary>
    public partial class Tables
    {
        public Interact.TbItemInfo TbItemInfo { get; }


        public Tables(System.Func<string, JArray> loader)
        {
            TbItemInfo = new Interact.TbItemInfo(loader("interact_tbiteminfo"));
            ResolveRef();
        }

        private void ResolveRef()
        {
            TbItemInfo.ResolveRef(this);
        }
    }

}

